# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pybug.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(731, 556)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.self_bugs_label = QtGui.QLabel(self.centralwidget)
        self.self_bugs_label.setObjectName(_fromUtf8("self_bugs_label"))
        self.horizontalLayout_3.addWidget(self.self_bugs_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.my_bugs_table = QtGui.QTableWidget(self.centralwidget)
        self.my_bugs_table.setAlternatingRowColors(True)
        self.my_bugs_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.my_bugs_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.my_bugs_table.setShowGrid(True)
        self.my_bugs_table.setGridStyle(QtCore.Qt.DotLine)
        self.my_bugs_table.setObjectName(_fromUtf8("my_bugs_table"))
        self.my_bugs_table.setColumnCount(3)
        self.my_bugs_table.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.my_bugs_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.my_bugs_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.my_bugs_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.my_bugs_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.my_bugs_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.my_bugs_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.my_bugs_table.setItem(0, 2, item)
        self.verticalLayout.addWidget(self.my_bugs_table)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.l3_bugs = QtGui.QLabel(self.centralwidget)
        self.l3_bugs.setObjectName(_fromUtf8("l3_bugs"))
        self.horizontalLayout_4.addWidget(self.l3_bugs)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.l3_bugs_table = QtGui.QTableView(self.centralwidget)
        self.l3_bugs_table.setObjectName(_fromUtf8("l3_bugs_table"))
        self.verticalLayout_3.addWidget(self.l3_bugs_table)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.common_bugs = QtGui.QLabel(self.centralwidget)
        self.common_bugs.setObjectName(_fromUtf8("common_bugs"))
        self.horizontalLayout_2.addWidget(self.common_bugs)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.common_bugs_table = QtGui.QTableView(self.centralwidget)
        self.common_bugs_table.setObjectName(_fromUtf8("common_bugs_table"))
        self.verticalLayout_2.addWidget(self.common_bugs_table)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.my_bugs_table, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QTableWidgetItem*)")), MainWindow.double_clicked)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.open_in_browser)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.self_bugs_label.setText(_translate("MainWindow", "TextLabel", None))
        self.my_bugs_table.setSortingEnabled(True)
        item = self.my_bugs_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "ddd", None))
        item = self.my_bugs_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.my_bugs_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.my_bugs_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Title", None))
        __sortingEnabled = self.my_bugs_table.isSortingEnabled()
        self.my_bugs_table.setSortingEnabled(False)
        item = self.my_bugs_table.item(0, 0)
        item.setText(_translate("MainWindow", "123", None))
        item = self.my_bugs_table.item(0, 1)
        item.setText(_translate("MainWindow", "NEW", None))
        item = self.my_bugs_table.item(0, 2)
        item.setText(_translate("MainWindow", "Crazy shit happened", None))
        self.my_bugs_table.setSortingEnabled(__sortingEnabled)
        self.l3_bugs.setText(_translate("MainWindow", "L3 Bugs", None))
        self.common_bugs.setText(_translate("MainWindow", "Common", None))
        self.pushButton.setText(_translate("MainWindow", "View in Browser", None))

